from __future__ import annotations

import json

_TEMPLATE = '''\
#!/usr/bin/env python3
"""
Auto-generated offline route executor for Kachaka Playground container.
DO NOT EDIT — generated by OfflineRouteGenerator.
"""
import json
import threading
import time
import urllib.request

import kachaka_api

# ── Embedded parameters ────────────────────────────────────────────────────────
RUN_ID = {run_id!r}
STOPS = json.loads({stops_json!r})
SHELF_NAME = {shelf_name!r}
DEFAULT_TIMEOUT = {default_timeout!r}
PI_URL = {pi_url!r}

# ── gRPC client (container-internal address) ───────────────────────────────────
GRPC_ADDRESS = "100.94.1.1:26400"
client = kachaka_api.KachakaApiClient(GRPC_ADDRESS)

# ── IMU shake detection ────────────────────────────────────────────────────────
ACCEL_THRESHOLD = 11.0   # m/s²
GYRO_THRESHOLD = 0.8     # rad/s

_imu_armed = False
_imu_lock = threading.Lock()
_shake_event = threading.Event()
_imu_samples = []
_imu_thread_stop = threading.Event()


def _imu_worker():
    """Background thread: poll IMU and trigger shake_event when armed + shake detected."""
    while not _imu_thread_stop.is_set():
        try:
            imu = client.get_ros_imu()
            accel_mag = (imu.linear_acceleration.x ** 2
                         + imu.linear_acceleration.y ** 2
                         + imu.linear_acceleration.z ** 2) ** 0.5
            gyro_mag = (imu.angular_velocity.x ** 2
                        + imu.angular_velocity.y ** 2
                        + imu.angular_velocity.z ** 2) ** 0.5
            exceeded = (accel_mag > ACCEL_THRESHOLD) or (gyro_mag > GYRO_THRESHOLD)

            with _imu_lock:
                _imu_samples.append(exceeded)
                if len(_imu_samples) > 3:
                    _imu_samples.pop(0)
                armed = _imu_armed
                triggered = armed and (len(_imu_samples) >= 3) and (sum(_imu_samples[-3:]) >= 2)

            if triggered:
                _shake_event.set()
        except Exception:
            pass
        time.sleep(0.1)


def _arm_imu(settle_delay=2.0):
    global _imu_armed
    _shake_event.clear()
    with _imu_lock:
        _imu_samples.clear()
    time.sleep(settle_delay)
    with _imu_lock:
        _imu_armed = True


def _disarm_imu():
    global _imu_armed
    with _imu_lock:
        _imu_armed = False
    _shake_event.clear()


# ── Report client ──────────────────────────────────────────────────────────────
_REPORT_URL = PI_URL + "/api/routes/offline/report"


def try_report(event, stop_index=None):
    """HTTP POST event to Pi. Silent on failure."""
    payload = {{"run_id": RUN_ID, "event": event, "stop_index": stop_index,
               "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S")}}
    try:
        data = json.dumps(payload).encode()
        req = urllib.request.Request(
            _REPORT_URL, data=data,
            headers={{"Content-Type": "application/json"}}, method="POST",
        )
        with urllib.request.urlopen(req, timeout=5):
            pass
    except Exception:
        pass


# ── Helpers ────────────────────────────────────────────────────────────────────

def _poll_until_done(timeout=120):
    """Block until the current robot command finishes."""
    deadline = time.time() + timeout
    time.sleep(1.0)
    while time.time() < deadline:
        try:
            state = client.get_command_state()
            # state has .state attribute: 0=PENDING, 1=RUNNING, etc.
            # When no command is running, command_id is empty
            if not state.command_id:
                return True
        except Exception:
            pass
        time.sleep(1.0)
    return False


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    print(f"[route_executor] Starting route {{RUN_ID}}")
    print(f"[route_executor] Shelf: {{SHELF_NAME}}, Stops: {{len(STOPS)}}")

    imu_thread = threading.Thread(target=_imu_worker, daemon=True)
    imu_thread.start()

    try:
        for i, stop in enumerate(STOPS):
            stop_name = stop["name"]
            timeout_sec = stop.get("timeout_sec") or DEFAULT_TIMEOUT
            print(f"[route_executor] Stop {{i+1}}/{{len(STOPS)}}: {{stop_name}}")

            # Move shelf to stop
            try_report("moving", i)
            client.move_shelf(SHELF_NAME, stop_name)
            _poll_until_done()
            try_report("arrived", i)

            # Announce arrival
            client.speak("到站，請取貨")
            print(f"[route_executor] Waiting for shake or timeout ({{timeout_sec}}s)")

            # Arm IMU with 2s settle delay, then wait
            _arm_imu(settle_delay=2.0)
            shook = _shake_event.wait(timeout=timeout_sec)
            _disarm_imu()

            if shook:
                print(f"[route_executor] Shake confirmed at {{stop_name}}")
                try_report("shake_confirmed", i)
            else:
                print(f"[route_executor] Timeout at {{stop_name}}")
                client.speak("超時，即將前往下一站")
                try_report("timeout", i)
                time.sleep(2.0)

        # Return shelf and go home
        print("[route_executor] Returning shelf and going home")
        client.return_shelf(SHELF_NAME)
        _poll_until_done(timeout=60)
        client.return_home()
        _poll_until_done(timeout=60)
        try_report("completed")
        print(f"[route_executor] Route {{RUN_ID}} completed")

    except Exception as exc:
        print(f"[route_executor] ERROR: {{exc}}")
        try_report("failed")
        try:
            client.return_shelf(SHELF_NAME)
            _poll_until_done(timeout=60)
        except Exception:
            pass
        try:
            client.return_home()
            _poll_until_done(timeout=60)
        except Exception:
            pass
    finally:
        _imu_thread_stop.set()
        imu_thread.join(timeout=2.0)


if __name__ == "__main__":
    main()
'''


class OfflineRouteGenerator:
    """Generates a self-contained Python script for the Kachaka Playground container."""

    def generate(
        self,
        run_id: str,
        stops: list[dict],
        shelf_name: str,
        default_timeout: int,
        pi_url: str,
    ) -> str:
        """Return a complete Python script string (route_executor.py content)."""
        stops_json = json.dumps(stops)
        return _TEMPLATE.format(
            run_id=run_id,
            stops_json=stops_json,
            shelf_name=shelf_name,
            default_timeout=default_timeout,
            pi_url=pi_url,
        )
