from __future__ import annotations

import json

_TEMPLATE = '''\
#!/usr/bin/env python3
"""
Auto-generated offline route executor for Kachaka Playground container.
DO NOT EDIT — generated by OfflineRouteGenerator.
"""
import json
import threading
import time
import urllib.request

import kachaka_api

# ── Embedded parameters ────────────────────────────────────────────────────────
RUN_ID = {run_id!r}
STOPS = json.loads({stops_json!r})
SHELF_NAME = {shelf_name!r}
DEFAULT_TIMEOUT = {default_timeout!r}
PI_URL = {pi_url!r}

# ── gRPC client (container-internal address) ───────────────────────────────────
GRPC_ADDRESS = "100.94.1.1:26400"
client = kachaka_api.KachakaApiClient(GRPC_ADDRESS)

# ── IMU shake detection ────────────────────────────────────────────────────────
ACCEL_THRESHOLD = 11.0   # m/s²
GYRO_THRESHOLD = 0.8     # rad/s

_imu_armed = False
_imu_lock = threading.Lock()
_shake_event = threading.Event()
_imu_samples = []           # ring buffer, max 3 recent samples
_imu_thread_stop = threading.Event()


def _imu_worker():
    """Background thread: poll IMU and trigger shake_event when armed + shake detected."""
    while not _imu_thread_stop.is_set():
        try:
            imu = client.get_ros_imu()
            ax = imu.linear_acceleration.x
            ay = imu.linear_acceleration.y
            az = imu.linear_acceleration.z
            gx = imu.angular_velocity.x
            gy = imu.angular_velocity.y
            gz = imu.angular_velocity.z

            accel_mag = (ax ** 2 + ay ** 2 + az ** 2) ** 0.5
            gyro_mag = (gx ** 2 + gy ** 2 + gz ** 2) ** 0.5
            exceeded = (accel_mag > ACCEL_THRESHOLD) or (gyro_mag > GYRO_THRESHOLD)

            with _imu_lock:
                _imu_samples.append(exceeded)
                if len(_imu_samples) > 3:
                    _imu_samples.pop(0)
                armed = _imu_armed
                triggered = armed and (len(_imu_samples) >= 3) and (sum(_imu_samples[-3:]) >= 2)

            if triggered:
                _shake_event.set()
        except Exception:
            pass
        time.sleep(0.1)


def _arm_imu(settle_delay: float = 2.0):
    global _imu_armed
    _shake_event.clear()
    with _imu_lock:
        _imu_samples.clear()
    time.sleep(settle_delay)
    with _imu_lock:
        _imu_armed = True


def _disarm_imu():
    global _imu_armed
    with _imu_lock:
        _imu_armed = False
    _shake_event.clear()


# ── Report client ──────────────────────────────────────────────────────────────
_REPORT_URL = PI_URL + "/api/routes/offline/report"


def try_report(event: str, extra: dict | None = None):
    """HTTP POST event to Pi. Silent on failure."""
    payload = {{"run_id": RUN_ID, "event": event}}
    if extra:
        payload.update(extra)
    try:
        data = json.dumps(payload).encode()
        req = urllib.request.Request(
            _REPORT_URL,
            data=data,
            headers={{"Content-Type": "application/json"}},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=5):
            pass
    except Exception:
        pass


# ── Helpers ────────────────────────────────────────────────────────────────────

def _resolve_shelf():
    """Return the shelf object matching SHELF_NAME."""
    shelves = client.get_shelves()
    for s in shelves:
        if s.name == SHELF_NAME:
            return s
    raise RuntimeError(f"Shelf not found: {{SHELF_NAME!r}}")


def _poll_until_done():
    """Block until the current robot command finishes."""
    while True:
        result = client.get_last_command_result()
        state = client.get_command_state()
        # state 0 = UNSPECIFIED/idle, 3 = SUCCEEDED, 4 = FAILED, 5 = CANCELLED
        if state in (0, 3, 4, 5):
            return result
        time.sleep(0.5)


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    imu_thread = threading.Thread(target=_imu_worker, daemon=True)
    imu_thread.start()

    shelf = _resolve_shelf()

    try:
        for stop in STOPS:
            stop_name = stop["name"]
            timeout_sec = stop.get("timeout_sec", DEFAULT_TIMEOUT)

            # Move shelf to stop
            try_report("moving", {{"stop": stop_name}})
            client.move_shelf(shelf.id, stop_name)
            _poll_until_done()

            try_report("arrived", {{"stop": stop_name}})
            client.speak("到站，請取貨")

            # Arm IMU with 2s settle delay
            _arm_imu(settle_delay=2.0)
            try_report("shake_confirmed", {{"stop": stop_name}}) if False else None  # placeholder

            # Wait for shake or timeout
            shook = _shake_event.wait(timeout=timeout_sec)
            _disarm_imu()

            if shook:
                try_report("shake_confirmed", {{"stop": stop_name}})
            else:
                client.speak("超時，即將前往下一站")
                try_report("timeout", {{"stop": stop_name}})

        # Return shelf and go home
        client.return_shelf(shelf.id)
        _poll_until_done()
        client.return_home()
        _poll_until_done()
        try_report("completed")

    except Exception as exc:
        try_report("failed", {{"error": str(exc)}})
        try:
            client.return_shelf(shelf.id)
            _poll_until_done()
        except Exception:
            pass
        try:
            client.return_home()
            _poll_until_done()
        except Exception:
            pass
        raise
    finally:
        _imu_thread_stop.set()
        imu_thread.join(timeout=2.0)


if __name__ == "__main__":
    main()
'''


class OfflineRouteGenerator:
    """Generates a self-contained Python script for the Kachaka Playground container."""

    def generate(
        self,
        run_id: str,
        stops: list[dict],
        shelf_name: str,
        default_timeout: int,
        pi_url: str,
    ) -> str:
        """Return a complete Python script string (route_executor.py content)."""
        stops_json = json.dumps(stops)
        return _TEMPLATE.format(
            run_id=run_id,
            stops_json=stops_json,
            shelf_name=shelf_name,
            default_timeout=default_timeout,
            pi_url=pi_url,
        )
